development:
  sessions:
    default:
      database: rails_meets_nosql_development
      hosts:
        - localhost:27017
      options:
        pool_size: 5
        timeout: 20
  options:
    use_activesupport_time_zone: true
test:
  sessions:
    default:
      database: rails_meets_nosql_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
        pool_size: 5
